from enum import Enum


class ErrorCode(str, Enum):
    INVALID_IMAGE = "INVALID_IMAGE"
    NO_FACE = "NO_FACE"
    MULTIPLE_FACES = "MULTIPLE_FACES"
    LOW_QUALITY = "LOW_QUALITY"
    LOW_SCORE = "LOW_SCORE"
    UNAUTHORIZED = "UNAUTHORIZED"
    FORBIDDEN = "FORBIDDEN"
    NOT_FOUND = "NOT_FOUND"
    MODEL_UNAVAILABLE = "MODEL_UNAVAILABLE"
